# yaml 配置
version: "3.7"
services:
  mysql:
    image: "mysql"
    ports:
      - "33306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "000000"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "000000"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"
  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 redis507:6379 -- ./bluebell_app ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8888:8084"